# Generated by Django 5.2.7 on 2025-10-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
