# Generated by Django 5.2.7 on 2025-10-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='in_calendar',
            field=models.BooleanField(default=False),
        ),
    ]
